### ISSUE TITLE
No static method Text-6FffQQw

### ISSUE THREAD

**Issue by Alexey-Gvozditskiy** [vanpra/compose-material-dialogs#106]
Faced with crash on Andrpoid 11. Release build
Kotlin: 1.5.21
Compose: 1.0.0
dialogs:datetime : 0.5.1

Fatal Exception: java.lang.NoSuchMethodError: No static method Text-6FffQQw(Ljava/lang/String;Lr0/f;JJLs1/i;Ls1/k;Ls1/e;JLx1/d;Lx1/c;JLx1/j;ZILjg/l;Lo1/a0;Lg0/i;III)V in class Lb0/b2; or its super classes (declaration of 'b0.b2' appears in /data/app/~~Yvt_fcC5qlxbVrHcdcbvRA==/com.basenjiapps.breeze-flMmsRusQBQJ1JrTJwEsuQ==/base.apk)
       at com.vanpra.composematerialdialogs.datetime.timepicker.TimePickerKt.TimePickerTitle-rAjV9yQ(TimePickerKt.java:908)
       at com.vanpra.composematerialdialogs.datetime.timepicker.TimePickerKt.TimePickerImpl(TimePickerKt.java:477)
       at com.vanpra.composematerialdialogs.datetime.timepicker.TimePickerKt.timepicker(TimePickerKt.java:564)
       at com._.SettingsPageKt$SettingsPage$1.invoke(SettingsPageKt.java:114)
       at com._.SettingsPageKt$SettingsPage$1.invoke(SettingsPageKt.java:10)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at com.vanpra.composematerialdialogs.MaterialDialog$build$2$2.invoke(MaterialDialog.java:177)
       at com.vanpra.composematerialdialogs.MaterialDialog$build$2$2.invoke(MaterialDialog.java:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at androidx.compose.material.SurfaceKt$Surface$6.invoke(SurfaceKt.java:223)
       at androidx.compose.material.SurfaceKt$Surface$6.invoke(SurfaceKt.java:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocalKt.java:28)
       at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(SurfaceKt.java:334)
       at androidx.compose.material.SurfaceKt.Surface-F-jzlyU(SurfaceKt.java:411)
       at com.vanpra.composematerialdialogs.MaterialDialog$build$2.invoke(MaterialDialog.java:147)
       at com.vanpra.composematerialdialogs.MaterialDialog$build$2.invoke(MaterialDialog.java:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at com.vanpra.composematerialdialogs.UtilsKt$ThemedDialog$1$1.invoke(UtilsKt.java:29)
       at com.vanpra.composematerialdialogs.UtilsKt$ThemedDialog$1$1.invoke(UtilsKt.java:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocalKt.java:28)
       at androidx.compose.material.TextKt.ProvideTextStyle(TextKt.java:92)
       at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialThemeKt.java:31)
       at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialThemeKt.java:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocalKt.java:28)
       at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialThemeKt.java:415)
       at com.vanpra.composematerialdialogs.UtilsKt$ThemedDialog$1.invoke(UtilsKt.java:43)
       at com.vanpra.composematerialdialogs.UtilsKt$ThemedDialog$1.invoke(UtilsKt.java:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1$2.invoke(AndroidDialog_androidKt.java:28)
       at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1$2.invoke(AndroidDialog_androidKt.java:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at androidx.compose.ui.window.AndroidDialog_androidKt.DialogLayout(AndroidDialog_androidKt.java:212)
       at androidx.compose.ui.window.AndroidDialog_androidKt.access$DialogLayout(AndroidDialog_androidKt.java)
       at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1.invoke(AndroidDialog_androidKt.java:44)
       at androidx.compose.ui.window.AndroidDialog_androidKt$Dialog$dialog$1$1$1.invoke(AndroidDialog_androidKt.java:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at androidx.compose.ui.window.DialogLayout.Content(DialogLayout.java:16)
       at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(AbstractComposeView.java:21)
       at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(AbstractComposeView.java:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocalKt.java:28)
       at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocalsKt.java:280)
       at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals_androidKt.java:31)
       at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals_androidKt.java:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocalKt.java:28)
       at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals_androidKt.java:274)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(WrappedComposition.java:27)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(WrappedComposition.java:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocalKt.java:28)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(WrappedComposition.java:157)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(WrappedComposition.java:8)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:48)
       at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambdaImpl.java:8)
       at androidx.compose.runtime.ComposerKt.invokeComposable(ComposerKt.java:15)
       at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(ComposerImpl.java:19)
       at androidx.compose.runtime.ComposerImpl$doCompose$2$5.invoke(ComposerImpl.java)
       at androidx.compose.runtime.SnapshotStateKt.observeDerivedStateRecalculations(SnapshotStateKt.java:46)
       at androidx.compose.runtime.ComposerImpl.doCompose(ComposerImpl.java:137)
       at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(ComposerImpl.java:18)
       at androidx.compose.runtime.CompositionImpl.composeContent(CompositionImpl.java:17)
       at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.java:33)
       at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(ComposerImpl.java:16)
       at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(ComposerImpl.java:16)
       at androidx.compose.runtime.ComposerImpl$CompositionContextImpl.composeInitial$runtime_release(ComposerImpl.java:16)
       at androidx.compose.runtime.CompositionImpl.setContent(CompositionImpl.java:15)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(WrappedComposition.java:87)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(WrappedComposition.java:2)
       at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.java:11)
       at androidx.compose.ui.platform.WrappedComposition.setContent(WrappedComposition.java:12)
       at androidx.compose.ui.platform.WrappedComposition.onStateChanged(WrappedComposition.java:28)
       at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:14)
       at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:92)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(WrappedComposition.java:48)
       at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(WrappedComposition.java:2)
       at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.java:122)
       at android.view.View.dispatchAttachedToWindow(View.java:22010)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4291)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
       at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:4298)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3107)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2590)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9939)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
       at android.view.Choreographer.doCallbacks(Choreographer.java:809)
       at android.view.Choreographer.doFrame(Choreographer.java:744)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

**Comment by vanpra** [comment]
I can't reproduce this error. Please let me know if it persists in the 0.6.0 release and if so I'll try and take another look.
