### ISSUE TITLE
Using Compose 1.1.0-beta04, kotlin 1.6.0, 0.6.1 DatePicker crash

### ISSUE THREAD

**Issue by skolson** [vanpra/compose-material-dialogs#120]
Attempting to use the above combination gets the callstack below. I'm guessing we need a version of compose-material-dialogs built with kotlin 1.6.0 and Compose 1.1.0-beta4 which is first release supporting Kotlin 1.6.0 and was just published yesterday (12-1-2021).
```
java.lang.NoSuchMethodError: No interface method item(Lkotlin/jvm/functions/Function3;)V in class Landroidx/compose/foundation/lazy/LazyGridScope; or its super classes (declaration of 'androidx.compose.foundation.lazy.LazyGridScope' appears in /data/app/~~nWlMKjGEZRQgCqXrCBOjvQ==/com.oldguy.monay-cdXrdeSUxyoY1MjuNdPIbw==/base.apk)
        at com.vanpra.composematerialdialogs.datetime.date.DatePickerKt$DayOfWeekHeader$1$1.invoke(DatePicker.kt:366)
        at com.vanpra.composematerialdialogs.datetime.date.DatePickerKt$DayOfWeekHeader$1$1.invoke(DatePicker.kt:364)
        at androidx.compose.foundation.lazy.LazyGridKt$FixedLazyGrid$1$1.invoke(LazyGrid.kt:252)
        at androidx.compose.foundation.lazy.LazyGridKt$FixedLazyGrid$1$1.invoke(LazyGrid.kt:250)
        at androidx.compose.foundation.lazy.LazyListItemsProviderImplKt$rememberStateOfItemsProvider$2$1.invoke(LazyListItemsProviderImpl.kt:50)
        at androidx.compose.foundation.lazy.LazyListItemsProviderImplKt$rememberStateOfItemsProvider$2$1.invoke(LazyListItemsProviderImpl.kt:49)
        at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:1798)
        at androidx.compose.runtime.DerivedSnapshotState.currentRecord(DerivedState.kt:117)
        at androidx.compose.runtime.DerivedSnapshotState.getDependencies(DerivedState.kt:172)
        at androidx.compose.runtime.CompositionImpl.recordReadOf(Composition.kt:587)
        at androidx.compose.runtime.Recomposer$readObserverOf$1.invoke(Recomposer.kt:792)
        at androidx.compose.runtime.Recomposer$readObserverOf$1.invoke(Recomposer.kt:792)
        at androidx.compose.runtime.snapshots.SnapshotKt$mergedReadObserver$1.invoke(Snapshot.kt:1332)
        at androidx.compose.runtime.snapshots.SnapshotKt$mergedReadObserver$1.invoke(Snapshot.kt:1331)
        at androidx.compose.runtime.DerivedSnapshotState.getValue(DerivedState.kt:160)
        at androidx.compose.foundation.lazy.LazyListKt.LazyList(LazyList.kt:104)
        at androidx.compose.foundation.lazy.LazyDslKt.LazyColumn(LazyDsl.kt:250)
        at androidx.compose.foundation.lazy.LazyGridKt.FixedLazyGrid(LazyGrid.kt:245)
        at androidx.compose.foundation.lazy.LazyGridKt.LazyVerticalGrid(LazyGrid.kt:63)
        at com.vanpra.composematerialdialogs.datetime.date.DatePickerKt.DayOfWeekHeader(DatePicker.kt:364)
        at com.vanpra.composematerialdialogs.datetime.date.DatePickerKt.CalendarView(DatePicker.kt:297)
        at com.vanpra.composematerialdialogs.datetime.date.DatePickerKt.access$CalendarView(DatePicker.kt:1)
        at com.vanpra.composematerialdialogs.datetime.date.DatePickerKt$DatePickerImpl$1$1.invoke(DatePicker.kt:135)
        at com.vanpra.composematerialdialogs.datetime.date.DatePickerKt$DatePickerImpl$1$1.invoke(DatePicker.kt:112)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at com.google.accompanist.pager.Pager$Pager$5$1$1.invoke(Pager.kt:274)
        at com.google.accompanist.pager.Pager$Pager$5$1$1.invoke(Pager.kt:263)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:135)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.foundation.lazy.LazyListScopeImpl$items$1$1.invoke(LazyListScopeImpl.kt:39)
        at androidx.compose.foundation.lazy.LazyListScopeImpl$items$1$1.invoke(LazyListScopeImpl.kt:39)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
        at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
        at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228)
        at androidx.compose.runtime.saveable.SaveableStateHolderImpl.SaveableStateProvider(SaveableStateHolder.kt:84)
        at androidx.compose.foundation.lazy.layout.LazyLayoutItemContentFactory$CachedItemContent$content$1.invoke(LazyLayoutItemContentFactory.kt:102)
```

**Comment by skolson** [comment]
I can make a PR upgrading a number of dependencies including compose and kotlin versions if that is helpful.

**Comment by LeoColman** [comment]
I'm not the project owner, but absolutely make a pr to fix this!

**Comment by risalfajar** [comment]
Great, now we have to wait, don't know how long.

**Comment by DevAtHeart** [comment]
Shouldn't this project use stable Compose versions?

**Comment by skolson** [comment]
This issue is specific to kotlin 1.6. The ONLY compose release built for kotlin 1.6 so far is the beta in the matching pull request. There is no other option. If you don't want/need kotlin 1.6, then use the earlier release.
When compose 1.1.0 goes stable, someone like me ( :-) ) will do another PR

**Comment by DevAtHeart** [comment]
Currently this library with version 0.6.1 pulls in compose:1.1.0-alpha05.

I  think it would be better to have full releases use stable dependencies while maybe having canary/beta/alpha/whatever releases that use newest but unstable dependencies
