### ISSUE TITLE
NoSuchMethodError for 1.0.0-alpha10 on DatePicker

### ISSUE THREAD

**Issue by MaaxGr** [vanpra/compose-material-dialogs#24]
Really early bug report for `1.0.0-alpha10`. No blame, but maybe it helps in solving.
This exception appears and the app crashes, when executing `dialog.show()` for a MaterialDialog-datepicker.

```
2021-01-13 21:06:29.184 15194-15194/de.maaxgr.homeoffice E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.maaxgr.homeoffice, PID: 15194
    java.lang.NoSuchMethodError: No virtual method emitNode(Ljava/lang/Object;)V in class Landroidx/compose/runtime/Composer; or its super classes (declaration of 'androidx.compose.runtime.Composer' appears in /data/app/~~p3fH6jJouuO_wBPaxVcjKQ==/de.maaxgr.homeoffice-2CyD3tUl1N_Pst0Yh-baRw==/base.apk)
        at com.vanpra.composematerialdialogs.MaterialDialog$build$2.invoke(MaterialDialog.kt:379)
        at com.vanpra.composematerialdialogs.MaterialDialog$build$2.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at com.vanpra.composematerialdialogs.UtilsKt$ThemedDialog$1$1.invoke(Utils.kt:24)
        at com.vanpra.composematerialdialogs.UtilsKt$ThemedDialog$1$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
        at androidx.compose.material.TextKt.ProvideTextStyle(Text.kt:246)
        at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(MaterialTheme.kt:83)
        at androidx.compose.material.MaterialThemeKt$MaterialTheme$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
        at androidx.compose.material.MaterialThemeKt.MaterialTheme(MaterialTheme.kt:74)
        at com.vanpra.composematerialdialogs.UtilsKt$ThemedDialog$1.invoke(Utils.kt:23)
        at com.vanpra.composematerialdialogs.UtilsKt$ThemedDialog$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.ui.window.AndroidDialogKt$ActualDialog$dialog$1$1$1$2.invoke(AndroidDialog.kt:110)
        at androidx.compose.ui.window.AndroidDialogKt$ActualDialog$dialog$1$1$1$2.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.ui.layout.LayoutKt.Layout(Layout.kt:668)
        at androidx.compose.ui.window.AndroidDialogKt.DialogLayout(AndroidDialog.kt:284)
        at androidx.compose.ui.window.AndroidDialogKt.access$DialogLayout(Unknown Source:0)
        at androidx.compose.ui.window.AndroidDialogKt$ActualDialog$dialog$1$1$1.invoke(AndroidDialog.kt:107)
        at androidx.compose.ui.window.AndroidDialogKt$ActualDialog$dialog$1$1$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.ui.window.DialogLayout.Content(AndroidDialog.kt:160)
        at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.kt:161)
        at androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
        at androidx.compose.ui.platform.AmbientsKt.ProvideCommonAmbients(Ambients.kt:276)
        at androidx.compose.ui.platform.AndroidAmbientsKt$ProvideAndroidAmbients$3.invoke(AndroidAmbients.kt:176)
        at androidx.compose.ui.platform.AndroidAmbientsKt$ProvideAndroidAmbients$3.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
2021-01-13 21:06:29.185 15194-15194/de.maaxgr.homeoffice E/AndroidRuntime:     at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
        at androidx.compose.ui.platform.AndroidAmbientsKt.ProvideAndroidAmbients(AndroidAmbients.kt:168)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.kt:261)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.AmbientKt.Providers(Ambient.kt:188)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.kt:260)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Unknown Source:10)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(ComposableLambda.kt:146)
        at androidx.compose.runtime.internal.ComposableLambda.invoke(Unknown Source:10)
        at androidx.compose.runtime.ComposerKt.invokeComposable(Composer.kt:2906)
        at androidx.compose.runtime.Composer.composeInitial(Composer.kt:2046)
        at androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:566)
        at androidx.compose.runtime.Composer$CompositionReferenceImpl.composeInitial$runtime_release(Composer.kt:2459)
        at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:109)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.kt:243)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Unknown Source:3)
        at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.kt:548)
        at androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.kt:234)
        at androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.kt:285)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:196)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.kt:241)
        at androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Unknown Source:3)
        at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.kt:617)
        at android.view.View.dispatchAttachedToWindow(View.java:20479)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3489)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3496)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2417)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:731)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-01-13 21:06:29.191 15194-15367/de.maaxgr.homeoffice V/StudioTransport: Handling agent command 1200 for pid: 15194.
2021-01-13 21:06:29.191 15194-15367/de.maaxgr.homeoffice V/StudioTransport: JNIEnv not attached
2021-01-13 21:06:29.241 15194-15194/de.maaxgr.homeoffice I/Process: Sending signal. PID: 15194 SIG: 9

```

**Comment by vanpra** [comment]
Thanks for the heads up on the new compose release. I've updated the library to the new version so everything should be working now.
