### ISSUE TITLE
App crashes on 12:xx pm hour selection

### ISSUE THREAD

**Issue by Moppet12** [vanpra/compose-material-dialogs#41]
When trying to select an hour after 12 pm (minutes doesn't matter), throws exception:

```
E/MessageQueue-JNI: java.time.DateTimeException: Invalid value for HourOfDay (valid values 0 - 23): 24
        at java.time.temporal.ValueRange.checkValidValue(ValueRange.java:311)
        at java.time.temporal.ChronoField.checkValidValue(ChronoField.java:730)
        at java.time.LocalTime.of(LocalTime.java:290)
        at com.vanpra.composematerialdialogs.datetime.SimpleLocalTime.toLocalTime(TimePicker.kt:89)
        at com.vanpra.composematerialdialogs.datetime.TimePickerKt$timepicker$3$1.invoke(TimePicker.kt:267)
        at com.vanpra.composematerialdialogs.datetime.TimePickerKt$timepicker$3$1.invoke(TimePicker.kt:266)
        at com.vanpra.composematerialdialogs.MaterialDialogButtons$positiveButton$2.invoke(MaterialDialogButtons.kt:87)
        at com.vanpra.composematerialdialogs.MaterialDialogButtons$positiveButton$2.invoke(MaterialDialogButtons.kt:78)
        at androidx.compose.foundation.ClickableKt$clickable$4$tap$1.invoke-k-4lQ0M(Clickable.kt:162)
        at androidx.compose.foundation.ClickableKt$clickable$4$tap$1.invoke(Clickable.kt:162)
        at androidx.compose.foundation.legacygestures.TapGestureFilter.onPointerEvent-H0pRuoY(TapGestureFilter.kt:119)
        at androidx.compose.ui.input.pointer.Node.dispatchToPointerInputFilter(HitPathTracker.kt:360)
        at androidx.compose.ui.input.pointer.Node.dispatchChanges(HitPathTracker.kt:308)
        at androidx.compose.ui.input.pointer.Node.dispatchChanges(HitPathTracker.kt:304)
        at androidx.compose.ui.input.pointer.Node.dispatchChanges(HitPathTracker.kt:304)
        at androidx.compose.ui.input.pointer.NodeParent.dispatchChanges(HitPathTracker.kt:179)
        at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:111)
        at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-gBdvCQM(PointerInputEventProcessor.kt:80)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:696)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3062)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3062)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3062)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3062)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:499)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1879)
        at android.app.Dialog.dispatchTouchEvent(Dialog.java:861)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:457)
        at android.view.View.dispatchPointerEvent(View.java:13725)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5582)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5385)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4888)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4941)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4907)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5047)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4915)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5104)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4888)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4941)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4907)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4915)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4888)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7660)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7594)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7555)
    	at android.view.ViewRootImpl$WindowI
```

This in version 0.3.1, I did not test in 0.3.2 because the "Ok" button doesn't appear in UI (which is another small bug I think).

**Comment by vanpra** [comment]
Thanks for letting me know about this bug. This should be fixed in the next release which I'll make in the next couple of days. As for the missing "Ok" button, this was done on purpose as it now allows you to define your own buttons with custom text messages. So you should be able to replicate the old UIand behaviour by adding the following code to your dialog:
``` 
buttons {
    positiveButton("Ok")
    negativeButton("Cancel")
}

```

**Comment by Moppet12** [comment]
Talking of these buttons, how am I supposed to add them? Sorry if gets out of issue's topic

**Comment by Moppet12** [comment]
Never mind, I just figured it out
