### ISSUE TITLE
Date Picker crashes

### ISSUE THREAD

**Issue by wakaztahir** [vanpra/compose-material-dialogs#51]
The Crash : 

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.wakaztahir.timeline, PID: 15573
    java.lang.NullPointerException
        at com.vanpra.composematerialdialogs.datetime.DatePickerKt.datepicker(DatePicker.kt:87)
        at com.wakaztahir.timeline.ui.dialogs.FilterDialogKt.FilterDialog(FilterDialog.kt:270)
        at com.wakaztahir.timeline.ui.dialogs.FilterDialogKt$FilterDialog$6.invoke(Unknown Source:6)
        at com.wakaztahir.timeline.ui.dialogs.FilterDialogKt$FilterDialog$6.invoke(Unknown Source:10)
        at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:91)
        at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2267)
        at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2514)
        at androidx.compose.runtime.ComposerImpl.recompose$runtime_release(Composer.kt:2640)
        at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:406)
        at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:733)
        at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:102)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:443)
        at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$2.invoke(Recomposer.kt:415)
        at androidx.compose.ui.platform.AndroidUiFrameClock$withFrameNanos$2$callback$1.doFrame(AndroidUiFrameClock.android.kt:34)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performFrameDispatch(AndroidUiDispatcher.android.kt:109)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performFrameDispatch(AndroidUiDispatcher.android.kt:41)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.doFrame(AndroidUiDispatcher.android.kt:69)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:970)
        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
        at android.view.Choreographer.doFrame(Choreographer.java:727)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
I/Process: Sending signal. PID: 15573 SIG: 9

```

My Code : 

```
        val dateCreatedDialog = remember {
            MaterialDialog()
        }
        dateCreatedDialog.datepicker()
        val dateEditedDialog = remember {
            MaterialDialog()
        }
        dateEditedDialog.datepicker{

        }
```

I have't even called show yet !

**Comment by wakaztahir** [comment]
I see the initial value for background color is null :

```
   DatePickerImpl(
        state = datePickerState,
        yearRange = yearRange,
        backgroundColor = dialogBackgroundColor!!
    )
```

And in Material Dialog
`
    var dialogBackgroundColor by mutableStateOf<Color?>(null)
`

**Comment by wakaztahir** [comment]
```
    implementation "io.github.vanpra.compose-material-dialogs:datetime:0.3.3"
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'
```

**Comment by wakaztahir** [comment]
val dateCreatedDialog = remember {
            MaterialDialog()
        }
        dateCreatedDialog.build {
            datepicker{

            }
        }
        val dateEditedDialog = remember {
            MaterialDialog()
        }
        dateEditedDialog.build {
            datepicker{

            }
        }
