### ISSUE TITLE
Error after upgrading to beta09

### ISSUE THREAD

**Issue by cloudappDave** [vanpra/compose-material-dialogs#87]
After updating my project to use jetpack compose beta09, there is an error when using a date picker:

java.lang.NoSuchMethodError: No static method Text-6FffQQw(Ljava/lang/String;Landroidx/compose/ui/Modifier;JJLandroidx/compose/ui/text/font/FontStyle;Landroidx/compose/ui/text/font/FontWeight;Landroidx/compose/ui/text/font/FontFamily;JLandroidx/compose/ui/text/style/TextDecoration;Landroidx/compose/ui/text/style/TextAlign;JLandroidx/compose/ui/text/style/TextOverflow;ZILkotlin/jvm/functions/Function1;Landroidx/compose/ui/text/TextStyle;Landroidx/compose/runtime/Composer;III)V in class Landroidx/compose/material/TextKt; or its super classes (declaration of 'androidx.compose.material.TextKt' appears in /data/app/~~y2vw2gGekTmp-TyLu1JDFw==/com.upkid.dev-63FF9nizyeJ9P_qVM48aTQ==/base.apk)
        at com.vanpra.composematerialdialogs.datetime.datepicker.DatePickerKt.CalendarHeader(DatePicker.kt:388)
        at com.vanpra.composematerialdialogs.datetime.datepicker.DatePickerKt.DatePickerImpl(DatePicker.kt:107)
        at com.vanpra.composematerialdialogs.datetime.datepicker.DatePickerKt.datepicker(DatePicker.kt:87)

**Comment by cloudappDave** [comment]
False alarm.  Needed to update to 0.4.3.  Thanks!
